# shellcheck shell=bash
# cloudinit.sh - build the cloud-init NoCloud seed (user-data + meta-data) as an
# ISO 9660 image labelled "cidata", using hdiutil (no third-party tools needed).

password_hash() { # reads plaintext from $1, prints a SHA-512 crypt hash
  local bin
  for bin in /opt/homebrew/opt/openssl@3/bin/openssl /usr/local/opt/openssl@3/bin/openssl openssl; do
    command -v "$bin" >/dev/null 2>&1 || continue
    if printf '%s' "$1" | "$bin" passwd -6 -stdin 2>/dev/null; then return 0; fi
  done
  return 1
}

cloudinit_generate() {
  local ci="$VM_DIR/cloud-init" pubkey host lock
  mkdir -p "$ci"
  [ -f "$VM_SSH_PUBKEY" ] || die "SSH public key not found: $VM_SSH_PUBKEY"
  pubkey="$(head -n 1 "$VM_SSH_PUBKEY")"
  host="${VM_NAME%%.*}"
  if [ -n "$VM_PASSWORD_HASH" ]; then lock=false; else lock=true; fi

  {
    printf 'instance-id: iid-%s-%s\n' "$VM_NAME" "$(date +%s)"
    printf 'local-hostname: %s\n' "$host"
  } > "$ci/meta-data"

  {
    echo '#cloud-config'
    echo "# generated by macvs on $(now_iso) - regenerate with: macvs reseed $VM_NAME"
    echo "hostname: $host"
    if [ "$host" != "$VM_NAME" ]; then
      echo "fqdn: $VM_NAME"
      echo 'prefer_fqdn_over_hostname: true'
    fi
    echo 'manage_etc_hosts: true'
    [ -n "$VM_TIMEZONE" ] && echo "timezone: $VM_TIMEZONE"
    cat <<EOT
users:
  - name: $VM_USER
    gecos: macvs administrator
    groups: [adm, sudo]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    lock_passwd: $lock
EOT
    [ -n "$VM_PASSWORD_HASH" ] && echo "    passwd: $VM_PASSWORD_HASH"
    cat <<EOT
    ssh_authorized_keys:
      - $pubkey
ssh_pwauth: false
disable_root: true
package_update: true
package_upgrade: false
final_message: "macvs: $VM_NAME is up after \$UPTIME seconds (cloud-init \$VERSION)"
EOT
  } > "$ci/user-data"
  chmod 600 "$ci/user-data"

  rm -f "$VM_SEED_PATH"
  hdiutil makehybrid -quiet -iso -joliet \
    -iso-volume-name cidata -joliet-volume-name cidata \
    -o "$VM_SEED_PATH" "$ci" >/dev/null \
    || die "hdiutil failed to build the cloud-init seed image"
  chmod 600 "$VM_SEED_PATH"
}
